version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./:/workdir
    working_dir: "/workdir"
    depends_on: 
      - redis 
  redis:
    image: "redis:alpine"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - "ALLOW_ANONYMOUS_LOGIN=yes"
  mongodb:
    image : mongo
    container_name: mongodb